### PR TITLE
Update to mill 0.10 and add _mill0.10 suffix

### PR DESCRIPTION
**Pull request by lolgab**
Adapted the build to cross-compile so when mill 0.11 is out.

### CODE REVIEW

**Comment by carueda** [comment]
@lolgab Thanks again for your updates. Just wondering, would you prefer you became a collaborator here and take care of these updates and merges yourself? Unfortunately I haven't been doing much Mill recently and you seem way more expert on it. I'd be happy to add you as collaborator if you think that would be a good way moving forward. Also open to other suggestions.

**Comment by lolgab** [comment]
Yeah, I might do that! This is a nice plugin and it would be nice if it could be updated and usable in the newest mill version.

**Comment by carueda** [comment]
@lolgab just one thought: things to add would be Github actions for ci and release to maven central, etc.  I'll try to look into that at some point but time is really scarce these days and I don't have a handy template that could be replicated here ..

**Comment by lolgab** [comment]
Makes sense! I'm doing it in #3 
Then you will need to add some secrets to the GitHub settings.
And you'll need to add the step as mandatory to merge PRs to the master branch.

**Pull request merged**
